from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('cart/',views.cart,name='cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('contact/',views.contact,name='contact'),
    path('shop-detail/',views.shop_detail,name='shop-detail'),
    path('shop/',views.shop,name='shop'),
    path('registe/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('change_password/',views.change_password,name='change_password'),
    path('forgot-password/',views.forgot_password,name='forgot-password'),
    path('verify-otp/',views.verify_otp,name='verify-otp'),
    path('new-password/',views.new_password,name='new-password'),
    path('profile/',views.profile,name='profile'),
    path('seller-index/',views.seller_index,name='seller-index'),
    path('seller-change_password/',views.seller_change_password,name='seller-change_password'),
    path('seller-add-product/',views.seller_add_product,name='seller-add-product'),
    path('seller-view-product/',views.seller_view_product,name='seller-view-product'),
    path('seller-product-detail/<int:pk>/',views.seller_product_detail,name='seller-product-detail'),
    path('seller-edit-product/<int:pk>/',views.seller_edit_product,name='seller-edit-product'),
    path('seller-delete-product/<int:pk>/',views.seller_delete_product,name='seller-delete-product'),
    path('detail/<int:pk>/',views.detail,name='detail'),
    path('add-to-wishlist/<int:pk>',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove-from-wishlist/<int:pk>/',views.remove_from_wishlist,name='remove-from-wishlist'),
    # path('product-detail/<int:pk>/',views.product_detail,name='product-detail'),
    path('add-to-cart/<int:pk>',views.add_to_cart,name='add-to-cart'),
    path('cart/<int:pk>/',views.cart,name='cart'),
    path('remove-from-cart/<int:pk>/',views.remove_from_cart,name='remove-from-cart'),
    path('change-qty/',views.change_qty,name='change-qty'),
    path('search/',views.search,name='search'),
    path('product100/',views.product100,name='product100'),
    path('product500/',views.product500,name='product500'),
    path('product1000/',views.product1000,name='product1000'),
    path('product10000/',views.product10000,name='product10000'),
    path('productS/',views.productS,name='productS'),
    path('productM/',views.productM,name='productM'),
    path('productL/',views.productL,name='productL'),
    path('productXL/',views.productXL,name='productXL'),
    path('productXXl/',views.productXXL,name='productXXL'),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('myorder/',views.myorder,name='myorder'),
    path('ajax/validate_email',views.validate_email,name='validate_email')

]